config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "users#index"

  get "/show", to: "welcome#show", as: :show_welcome

  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:index, :show, :new, :create, :destroy]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.admin?
      can :manage, :all # Admin can perform any action on any resource
    else
      can :read, :all # Guests and regular users can read any resource

      if user.id
        can :create, Post if user.present?
        can :create, Comment if user.present?
        can :update, Post, user_id: user.id

        can :destroy, Post, author_id: user.id # Allow users to delete their own posts
        can :destroy, Comment, user_id: user.id # Allow users to delete their own comments
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true

  after_save :update_post_comments_counter
  after_destroy :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_post_likes_counter
  after_destroy :update_post_likes_counter

  private

  def update_post_likes_counter
    post.increment!(:likes_counter) if persisted?
    post.decrement!(:likes_counter) if destroyed?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # , :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  attribute :posts_counter, :integer, default: 0

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def delete_user_from_database
    destroy
  end

  enum role: %i[user admin moderator] # Add any roles you need

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      before_action :authenticate_user!

      def index
        @post = Post.find(params[:post_id])
        render json: @post.comments
      end

      def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user
        if @comment.save
          render json: @comment, status: :created
        else
          render json: @comment.errors, status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.require(:comment).permit(:content)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @user = User.find(params[:user_id])
        @posts = @user.posts.includes(:comments)
        render json: @posts
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = @user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: post_path(@post), notice: 'Comment was successfully deleted.')
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: params[:user_id], post_id: params[:post_id])
    redirect_to posts_path
  end

  def destroy
    @like = Like.includes(:user, :post).find(params[:id])
    @like.destroy
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
require 'will_paginate/array'
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @page = params.fetch(:page, 0).to_i
    @posts = @user.posts.includes(:comments).limit(3).offset(@page * 3)
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  def show
    @post = Post.includes(:author).find(params[:id])
    @user = @post.author
    @likes_count = @post.likes_counter
  end

  def like
    @post = Post.includes(:author).find(params[:id])
    @like = Like.create(user: current_user, post: @post)

    respond_to do |format|
      format.json { render json: { likes_count: @post.likes.count } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1 class='text-3xl mb-8 font-medium'>New Comment</h1>

<%= form_for(@comment, url: user_post_comments_path(@user, @post)) do |f| %>
  <div>
    <div>
      <%= f.label :text %>
    </div>

    <div class='mt-4'>
      <%= f.text_area :text %>
    </div>

    <div class='mt-4'>
      <%= f.submit 'Create Comment', class: 'bg-green-500 cursor-pointer rounded-md px-4 py-2 text-white' %>
    </div> 
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col justify-start items-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

  </body>
</html>

app/views/login/index.html.erb
<section class='border'>
<form>
  <div>
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
  </div>
  <div>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
  </div>
  <div>
    <input type="submit" value="Submit">
  </div>
</form>
</section>

app/views/posts/index.html.erb
<section class='flex flex-col w-[500px] mb-[5rem] justify-start items-center'>
  <section class='w-[500px] border-black'>
    <h1 class='font-medium text-4xl font-medium mb-4'>All Posts by <%= @user.name %></h1>
    <p class='font-medium mb-2'>Number of Posts: <%= @user.posts.count %></p>
    <%= render '/shared/userprofile' %>
    
    <ul class='w-full mt-8 flex flex-col justify-start w-full items-start gap-4'>
      <% @posts.each_with_index do |post, index| %>
        <li>
          <%= render '/shared/post', post: post, show_comments: true %>
        </li>
      <% end %>
    </ul>
    
    <button class='mt-8 mr-4 px-6 py-2 rounded-md bg-blue-500 text-white font-medium'>
      <span><%= link_to 'Next', user_posts_path(page: (@page.to_i + 1)), class: 'btn' %></span>
    </button>

    <% if @page.to_i > 0 %>
      <button class='mt-4 ml-4 p-x-6 py-2 font-medium bg-blue-500 text-white rounded-md'>
        <%= link_to 'Prev', user_posts_path(page: (@page.to_i - 1)), class: 'btn' %>
      </button>
    <% end %>
      
    <div class='mt-4 font-semibold'>
      <%= link_to 'Back to Profile', user_path(@user), class: 'btn' %>
    </div>
  </section>
</section>

app/views/posts/like.js.erb
// like.js.erb
console.log("Like JS executed!");

let postId = <%= post.id %>;
let likesCount = <%= post.likes.count %>;
document.getElementById("likes-count-" + postId).textContent = likesCount;

app/views/posts/new.html.erb
<h1 class='font-medium text-3xl mb-8'>Create New Post</h1>
<%= form_for(@post, url: user_posts_path(@user)) do |f| %>
  <div>
    <div>
      <p class='font-medium'><%= f.label :title %></p>
      <%= f.text_field :title %>
    </div>
    <div class='mt-8'>
      <p class='font-medium'><%= f.label :text %></p>
      <%= f.text_area :text %>
    </div>
  </div>
  <%= button_tag(type: 'submit', class: 'mt-8 text-white px-6 py-2 bg-blue-500 cursor-pointer boder-2 border-black rounded-md') do %>
  Create Post
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1 class='font-semibold text-3xl mb-6'><%= @post.title %></h1>

<div class='mt-8'>
  <%= link_to 'Back to Posts', user_posts_path(@post.author) %>
</div>

<section class='w-[500px] border mb-[5rem]'>
  <div class='flex justify-between items-center'>
    <p class='font-medium'>Post <%= @post.id %> by <%= @post.author.name %></p>
    <p class='text-[14px]'>Comments: <%= @post.comments.count %> Likes <%= @post.likes.count %></p>
  </div>

  <div class='mt-8'>
    <p><%= @post.text %></p>
  </div>
  
  <div class='mt-8'>
    <p class='font-medium'>Comments</p>
    <ul class='mt-4'>
      <%= render '/shared/comment_list', post: @post %>
    </ul>
  </div>

  <button class='mt-8 px-4 py-2 bg-blue-500 rounded-md text-white'>
    <%= link_to 'Create New Comment', new_user_post_comment_path(@post.author, @post) %>
  </button>
</section>

  
</section>

app/views/shared/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <li class='mb-4'>
    <p class='font-medium'><%= comment.user.name %></p>
    <p><%= comment.text %></p>
    <% if can? :destroy, comment %>
      <%= button_to 'Delete Comment', [comment.user, post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-white px-6 py-2 bg-red-500 rounded-md mt-4' %>
    <% end %>
  </li>
<% end %>

app/views/shared/_post.html.erb
<div class='border border-black rounded-md p-4'>
  <%= link_to user_post_path(@user, post), class:'inline-block' do %>
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
  <% end %>
  <div class='mt-4 flex border border-black w-auto justify-end items-center gap-x-4 text-sm'>
    <span>Comments: <%= post.comments.count %></span>
    <span class='my-4 flex justify-end items-center gap-4 text-sm'>
      <%= button_to 'Like', post_likes_path(post, user_id: @user.id), method: :post, class: 'bg-orange-500 px-4 py-2 rounded-md text-white', remote: true %>
      <span><span id="likes-count"><%= post.likes.count %></span></span>  
    </span>
    <span><%= link_to 'Comment', new_user_post_comment_path(@user, post), class: 'bg-blue-500 px-4 py-2 rounded-md text-white' %></span>
  </div>

  <% if can? :destroy, post %>
    <%= button_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>

  <% if show_comments %>
    <%= render '/shared/comment_list', post: post %>
  <% end %>
</div>  

app/views/shared/_userprofile.html.erb
<div class='border cursor-pointer px-6 border-black h-[100px] flex items-center justify-start w-full gap-4'>
  <div class='h-[60px] w-[60px] rounded-full border '>
    <% if @user.photo.present? %>
      <img src="<%= @user.photo %>" class='w-full h-full object-cover' alt="Photo">
    <% end %>
  </div>
  <div>
    <a href="<%= user_path(@user) %>">
      <p><%= @user.name %></p>
    </a>
  </div>
</div>

<button class='py-2 px-4 bg-green-500 text-white rounded-md border font-medium mt-4'>
  <%= link_to 'Create New Post', new_user_post_path(@user), class: 'btn' %>
</button>

app/views/users/index.html.erb
<section class='border-orange-400 w-full flex flex-col justify-start items-center'>
  <h1 class='text-4xl font-semibold'>List of users</h1>

  <ul class='border-black mt-8 mb-[4rem] flex flex-col justify-start items-start gap-4'>
    <% @users.each do |user| %>
      <li class='border-2 cursor-pointer px-6 border-orange-500 rounded-md w-[500px] h-[100px] flex items-center justify-start gap-4'>
        <div class='h-[60px] w-[60px] rounded-full border '>
          <% if user.photo.present? %>
            <img src="<%= user.photo %>" class='w-full h-full object-cover' alt="Photo">
          <% end %>
        </div>
        <div>
          <a href="<%= user_path(user) %>">
            <p><%= user.name %></p>
            <p class='text-xs'><%= user.posts_counter %> posts</p>
          </a>
        </div>
      </li>
    <% end %>
  </ul>

  

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>New User</h1>

<p>This is a placeholder text for the new user page. You can customize it as needed.</p>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<section class='flex flex-col w-[500px] justify-start items-center mb-[5rem]'>
  <h1 class='text-4xl mb-4 font-medium'>User Details</h1>
  
  <section class='w-[500px] border-orange-300'>
    <%= render '/shared/userprofile' %>

    <div class='border-2 border-black mt-8'>
      <p>Bio: <%= @user.bio %></p>
    </div>

    <div class='mt-8 flex flex-col justify-start start-center gap-4'>
      <h2 class='font-medium'>Posts by <%= @user.name %></h2>
      <p class='font-medium'>Number of Posts: <%= @user.posts.count %></p>
      <% @user.recent_posts.each do |post| %>
        <%= render '/shared/post', post: post, show_comments: false %>
      <% end %>
    </div>

    <button class='mt-8 px-6 py-2 text-white bg-blue-500 rounded-md'>
      <%= link_to 'All Posts', user_posts_path(@user) %>
    </button>

    <button class='font-medium text-xl ml-4 text-orange-500 hover:underline'>
      <%= link_to 'Users List', users_path %>
    </button>
  </section>
</section>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to My Blog</title>
</head>
<body>
  <h1>Welcome to My Blog</h1>
  <p>This is the home page of my blog.</p>
</body>
</html>

app/views/welcome/show.html.erb
<h1>Welcome show</h1>